### ISSUE TITLE
mode=‘month’可以设置默认展示其他月份吗

### ISSUE THREAD

**Issue by wangzhequan** [Hzy0913/mpvue-calendar#112]

**Comment by wangzhequan** [comment]
mode= ‘week’也一样，可以设置显示其他周吗

**Comment by Hzy0913** [comment]
可以调用内部的`render`方法，使用与`setToday`方式相同
[render函数](https://github.com/Hzy0913/mpvue-calendar/blob/master/src/mpvue-calendar.vue#L373)
[setToday方法使用](https://github.com/Hzy0913/mpvue-calendar/blob/master/example/App.vue#L134)
