### ISSUE TITLE
能用demi 做一个适配vue2的项目吗？

### ISSUE THREAD

**Issue by 775174143** [Hzy0913/mpvue-calendar#127]
能用demi 做一个适配vue2的项目吗？

**Comment by Hzy0913** [comment]
安装 [mpvue-calendar](https://www.npmjs.com/package/mpvue-calendar/v/2.3.7) 大版本为2的支持vue2，但部分能力没有，如手势滑动等 [@2.x分支](https://github.com/Hzy0913/mpvue-calendar/tree/mpvue-calendar%402.x)
