### ISSUE TITLE
好吧，又是我。这次是组件数据渲染的问题

### ISSUE THREAD

**Issue by PythonNaChen** [Hzy0913/mpvue-calendar#13]
正常：我在日历显示系统时间 2018年九月份的时候， 提交了 比如 十月份（反正不是当前显示的月份） 的某些天的日期给后台，提交成功后，切换到十月份的日历能够看到我刚提交的那些日期已经被我标注的class渲染了样式，返回格式：[{date: '2018-9-20', className: 'holiday'}]）

    异常：如果我修改提交的日期是页面显示的月份（比如我切换到十一月份，去提交当前显示的这个十一月的某些日期，），在提交成功后，当前日期的数据并没有被class渲染（dom没有更新），必须切到上个月或者下个月，再返回到十一月才能看到数据修改后的样式渲染

**Comment by Hzy0913** [comment]
由于暂时没有支持`tileContent `监听变化，后续会进行支持。可以手动调用`renderer(year, month)`方法重新渲染页面
```javascript
this.$refs.calendar.renderer(2018, 8); //渲染2018年8月份
```

**Comment by PythonNaChen** [comment]
> 由于暂时没有支持`tileContent`监听变化，后续会进行支持。可以手动调用`renderer(year, month)`方法重新渲染页面
> 
> ```js
> this.$refs.calendar.renderer(2018, 8); //渲染2018年8月份
> ```

thirdScriptError
number is not defined;at pages/schedule/main handleProxy function;at api request success callback function
ReferenceError: number is not defined

**Comment by Hzy0913** [comment]
https://github.com/Hzy0913/mpvue-calendar/issues/11  看这个吧，晚点我更新一下

**Comment by Hzy0913** [comment]
@1.3.2版本修复renderer方法错误，并且监听`tileContent `和`almanacs `参数变化

**Comment by shen-lan** [comment]
`this.$refs.calendar.renderer(2018, 8);
重新渲染有问题。
官方 [demo](http://preview.binlive.cn/mpvue-calendar#/)
比如：先选择区间 2018.9.8-2018.9.10
再点击渲染指定月份 ，再回到9月份，发现刚选择的9月份区间竟然还在。
