### ISSUE TITLE
请教一下关于打包问题

### ISSUE THREAD

**Issue by Kexin-Li** [Hzy0913/mpvue-calendar#19]
Hi，想请教你一个问题～

我注意到你的组件并没有经过打包处理，而是直接输出vue文件。这样的话我在自己的项目中引入你的组件就相当于直接引入了一个vue文件。

现在我想封装一个mpvue组件，但是可能会在vue文件中写一些es6，所以想要经过打包处理一下vue文件。但是vue-loader会将我的vue文件转化为js文件，这样的话微信小程序中的mpvue就不认识了。

想请教一下您有没有遇到过类似问题呢？

**Comment by Hzy0913** [comment]
mpvue-loader应该是分析.vue组件来生成对应的微信小程序规范的模版，不过mpvue-loader应该可正常编译绝大部分es6+的语法吧

**Comment by Kexin-Li** [comment]
那假如我想像你的组件一样封装一个组件然后发到npm上，再在自己的项目中引入这个组件，这样的话它就会存在我的项目中的`node_modules`目录下面，可是mpvue-loader在打包的时候又不会编译`node_modules`下面的东西。

我现在就遇到了这个错误，报错不能识别es6的语法。然后发现是引入的自己的组件没有被编译成es5。😂

**Comment by Hzy0913** [comment]
babel-loader配置下include目录

**Comment by Kexin-Li** [comment]
我试一下～谢谢你的意见！
