### ISSUE TITLE
请问怎样让它只显示上面两行

### ISSUE THREAD

**Issue by lingchuanzhou** [Hzy0913/mpvue-calendar#20]
请问怎样让它只显示上面两行，就只要星期那一行，以及第一行的日期：
![image](https://user-images.githubusercontent.com/16234589/50725331-1bdf4000-1137-11e9-8e54-075e6258eb7e.png)

**Comment by RichChen1015** [comment]
请教一下，怎么按周切换

**Comment by Hzy0913** [comment]
@2.1.1版本已支持按周切换

**Comment by lingchuanzhou** [comment]
谢谢~
