### ISSUE TITLE
disabled参数添加之后报错

### ISSUE THREAD

**Issue by wkl007** [Hzy0913/mpvue-calendar#21]
```
<Calendar
        :disabled="['2019-2-27']"
 />
```
![在这里插入图片描述](https://img-blog.csdnimg.cn/20190129113224912.png)

**Comment by Hzy0913** [comment]
你用的哪个版本？刚发布的@2.1.0版本改动比较大可能有些问题，可以切到比较稳定的@2.0.13

**Comment by wkl007** [comment]
我用的最新版本，我切一下版本看看
