### ISSUE TITLE
升级mpvue到2.0.0后公历和月份切换不显示了

### ISSUE THREAD

**Issue by iworkcloud** [Hzy0913/mpvue-calendar#23]
如题。
![image](https://user-images.githubusercontent.com/2082094/53004411-18e0aa80-346c-11e9-8327-886725970b13.png)

**Comment by Hzy0913** [comment]
你具体是哪个版本呢？可以试下@2.1.1

**Comment by iworkcloud** [comment]
> 你具体是哪个版本呢？可以试下@2.1.1

mpvue-calendar用的就是2.1.1
![image](https://user-images.githubusercontent.com/2082094/53058012-6ef53280-34ec-11e9-9ca3-1e13cb427842.png)

**Comment by Hzy0913** [comment]
试了官方提供的脚手架模版没有复现，你是否配套的相关工具没有配置正确
<img width="493" alt="wechat6b8d3ef8e80f82d8ac1342c0d8562da1" src="https://user-images.githubusercontent.com/22450881/53065059-0e262400-3505-11e9-8903-de2b79f116c7.png">

**Comment by iworkcloud** [comment]
> > 你具体是哪个版本呢？可以试下@2.1.1
> 
> mpvue-calendar用的就是2.1.1
> ![image](https://user-images.githubusercontent.com/2082094/53058012-6ef53280-34ec-11e9-9ca3-1e13cb427842.png)

谢谢你，我再找找原因。

**Comment by iworkcloud** [comment]
重新按照MPVUE2.0的升级指导安装了一遍，可以了。谢谢！
