### ISSUE TITLE
返回今日的时候有bug

### ISSUE THREAD

**Issue by alasai** [Hzy0913/mpvue-calendar#26]
返回今日之后，
![default](https://user-images.githubusercontent.com/26901102/53717964-c1433580-3e94-11e9-8e09-fd0f9592d95c.png)
应该是如下的效果
![default](https://user-images.githubusercontent.com/26901102/53717975-d1f3ab80-3e94-11e9-9b54-9b0762675a43.png)
点击下个月5号，但是5号没有选中，而是显示整个下个月

**Comment by Hzy0913** [comment]
返回今日时候没有设置自动选中当日日期，如有需要可以自己设置value为当天日期。点击上下月份时候的设计就是只进行翻页功能
