### ISSUE TITLE
切换到上个月不会触发 `selectMonth` 事件

### ISSUE THREAD

**Issue by NateScarlet** [Hzy0913/mpvue-calendar#28]
https://github.com/Hzy0913/mpvue-calendar/blob/9c71be0cd18e6faad49c51d5a1f9a11044095805/src/mpvue-calendar.vue#L910-L913
https://github.com/Hzy0913/mpvue-calendar/blob/9c71be0cd18e6faad49c51d5a1f9a11044095805/src/mpvue-calendar.vue#L858-L861

![image](https://user-images.githubusercontent.com/21083014/54265180-afa61000-45af-11e9-95d8-fc97befdca38.png)

**Comment by Hzy0913** [comment]
感谢反馈 👍

**Comment by Hzy0913** [comment]
@2.2.2版本删除`prev`和`next`切换月份时触发`selectMonth` 事件
