### ISSUE TITLE
tileContent 属性设置有问题

### ISSUE THREAD

**Issue by cikecool** [Hzy0913/mpvue-calendar#34]
我使用的是 chrom浏览器

return {
      value: [],
      isrange: false,
      weekSwitch: false,
      ismulti: false,
      dataInfo: {},
      monFirst: true,
      clean: false, //简洁模式
      lunar: true, //显示农历
      events: {'2019-2-7':'今日备注', '2019-2-8':'一条很长的明日备注'},
      tileContent: [],
      renderValues: [],
      disabledArray: ['2019-1-27','2019-2-25'],
      almanacs: {'4-14': '学生日', '11-22': '感恩日'},
      search:{
        startDate:null,
        endDate : null,
        month : ''
      },
    }

methods: {
    load(){
      tool.service.workdayAndHoliday.queryWHEnterpriseSet(this.search).then((result)=>{
        var dataList = result.dataList;
        this.tileContent = []
        for(let j = 0,len =  dataList.length; j < len; j++){
         if(dataList[j].status===2){
            var _day = {className: 'xiu', content: '假'};
            _day.date = this.formatDateMD(dataList[j].date);
            this.tileContent.push(_day);
          }else if(dataList[j].status===3){
            var _day = { className: 'ban', content: '班'};
            _day.date = this.formatDateMD(dataList[j].date);
            this.tileContent.push(_day);
          }
        }
      })
    },

tileContent    赋值过之后 ，点击多个日期，  会显示多个日期被选中，样式类似日期muti样式

**Comment by Hzy0913** [comment]
哪个版本呢？ 没有复现
