### ISSUE TITLE
周模式，使用value设置了不是当前的周的时间周日历没有对应切换

### ISSUE THREAD

**Issue by flzyup** [Hzy0913/mpvue-calendar#38]
RT，周模式下，设置了时间不是本周，即后面一周时，当天日期选择是高亮的，但是周日历并没有切换到后面一周，而是本周
![image](https://user-images.githubusercontent.com/158452/57736298-03c98f80-76da-11e9-8ef6-6de301879b7b.png)
![image](https://user-images.githubusercontent.com/158452/57736307-0af09d80-76da-11e9-95ca-86b52db8fe08.png)
其实我选中的是05-24这天，但是数据修改后，周日历还是在本周，而不是05-24这周

**Comment by Hzy0913** [comment]
后期会修复，暂时可以在设置value后手动调用一下
 `this.$refs.calendar.renderer(2019, 5, '24')` //渲染2019年5月份24日，24为字符串类型。
`renderer`用法可以查看文档或example

**Comment by flzyup** [comment]
好 我试试

**Comment by Hzy0913** [comment]
@2.2.2 已修复该问题，设置`value`会触发自动渲染

**Comment by flzyup** [comment]
好 我更新下 谢谢

**Comment by flzyup** [comment]
我在onLoad()方法的时候会去加载已经选中的日期，当我第一次进入的时候，能正确选中对应日期并高亮，如果返回上级页面再次进入的时候，就不会跳转到对应的这个日期了

**Comment by Tzrong** [comment]
<Calendar lunar clean ref="calendar" @select="selectDate" :range="true"></Calendar>
在退出页面的时候设置this.$refs.calendar.value = []再次进入页面的时候 之前选中的日期还是处于被选中的状态 

期望：希望退出页面的时候 之前选中的日期清空

**Comment by Hzy0913** [comment]
@Tzrong 组件卸载时设置`value=[]`，即可清空选中日期
