### ISSUE TITLE
如何让他开始就显示为单选模式？

### ISSUE THREAD

**Issue by yywwone** [Hzy0913/mpvue-calendar#39]

**Comment by Hzy0913** [comment]
不设置  `range` 和  `multi` 参数，或都为 `false` 时为单选模式

**Comment by yywwone** [comment]
打印日期，如果我想要每次重新选择日期 然后打印日期详情应该用什么函数呢

**Comment by Hzy0913** [comment]
https://github.com/Hzy0913/mpvue-calendar/blob/master/example/components/Calendar.vue#L176
