### ISSUE TITLE
请问箭头图片是怎样解决的，在真机上是看不到左右那两个蓝色的箭头？

### ISSUE THREAD

**Issue by Goular** [Hzy0913/mpvue-calendar#4]
<span class="calendar-prev" @click="prev">
            <img src="./arrow-left.png" >
          </span>
          <span class="calendar-next"  @click="next">
              <img src="./arrow-right.png" alt="">
          </span>

他并没有打包到dist文件夹的路径上？

**Comment by Hzy0913** [comment]
@Goular  多谢，已更新，安装最新@1.0.3版本即可，并且新增可以自定义箭头图片，具体可以看readme
