### ISSUE TITLE
请问 range 模式下必须选择两个日期 select才能返回 选择的信息吗？

### ISSUE THREAD

**Issue by yfzhangCode** [Hzy0913/mpvue-calendar#44]

**Comment by Hzy0913** [comment]
是的，现在是这么设计的

**Comment by yfzhangCode** [comment]
@Hzy0913  你好， 关于这个小修改了一下，，但是没有提交权限。。不知道会不会对其他有影响，希望可以得到指正。。谢谢
具体修改：
![image](https://user-images.githubusercontent.com/24284536/59476666-67371080-8e84-11e9-9c02-ff8fed55f6d1.png)
![image](https://user-images.githubusercontent.com/24284536/59476681-7a49e080-8e84-11e9-970d-4fc4a19772ed.png)

**Comment by Hzy0913** [comment]
👍   这个之前已经更新了代码，下次更新版本的时候会增加该功能。
[详见代码改动位置](https://github.com/Hzy0913/mpvue-calendar/blob/master/src/mpvue-calendar.vue#L1024)
