### ISSUE TITLE
weekSwitch 模式下动态 改变 true或者false时，需要触发两次事件才能渲染日历

### ISSUE THREAD

**Issue by yfzhangCode** [Hzy0913/mpvue-calendar#45]

**Comment by yfzhangCode** [comment]
楼主 可以添加 监听weekSwitch的需求吗
![image](https://user-images.githubusercontent.com/24284536/59478689-cb5dd280-8e8c-11e9-9632-87ff4ff545de.png)

**Comment by Hzy0913** [comment]
感谢反馈，也可以尝试提交PR
