### ISSUE TITLE
没有写completion补全了上月下月数据，是为什么

### ISSUE THREAD

**Issue by zhangxiaoru** [Hzy0913/mpvue-calendar#48]
![image](https://user-images.githubusercontent.com/15326045/60228544-90649180-98c5-11e9-986f-88cd5db0c8c1.png)
![image](https://user-images.githubusercontent.com/15326045/60228557-9b1f2680-98c5-11e9-881a-a1614db9e114.png)

**Comment by Hzy0913** [comment]
`completion` 参数补全是指会把每个月都以相同的6行补全，如果不想显示首末行上下个月份的数据可以通过标签上的`month-last-date` 和`mc-next-month`, 设置透明度来控制

**Comment by Hzy0913** [comment]
`completion` 参数补全是指会把每个月都以相同的6行补全。如果不想展示首末行上下个月份的数据，可以通过标签上的`mc-last-month` 和`mc-next-month`的类名, 设置透明度来控制显示
