### ISSUE TITLE
是否可以不补全日期

### ISSUE THREAD

**Issue by circlewang** [Hzy0913/mpvue-calendar#53]
在completion默认为false的时候，也不用上个月的日期来补全日历，不知道怎么实现呢

**Comment by Hzy0913** [comment]
可以参考一下这个issues https://github.com/Hzy0913/mpvue-calendar/issues/48

**Comment by circlewang** [comment]
好的，谢谢，很有帮助

在 2019-08-05 15:16:16，"飞翔的荷兰人" <notifications@github.com> 写道：


可以参考一下这个issues #48
