### ISSUE TITLE
build的时候不支持关键字const  编译报错

### ISSUE THREAD

**Issue by Yan1513149392** [Hzy0913/mpvue-calendar#57]
![QQ图片20190904155554](https://user-images.githubusercontent.com/30859526/64236188-76ca7080-cf2c-11e9-8d58-efa95e1376da.png)
![image](https://user-images.githubusercontent.com/30859526/64236242-93ff3f00-cf2c-11e9-8e8f-857540bfe3e8.png)
关键字 const  修改成var打包成功

**Comment by Hzy0913** [comment]
感谢反馈，已替换const关键字

**Comment by Yan1513149392** [comment]
感谢更新

**Comment by Yan1513149392** [comment]
感谢处理了该问题，辛苦了


------------------
 颜培才
手机：18824918090
QQ：1513149392
 微信：




 




------------------ 原始邮件 ------------------
发件人: "飞翔的荷兰人"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 上午9:44
收件人: "Hzy0913/mpvue-calendar"<mpvue-calendar@noreply.github.com>;
抄送: "颜培才"<1513149392@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Hzy0913/mpvue-calendar] build的时候不支持关键字const  编译报错 (#57)




感谢反馈，已替换const关键字

**Comment by Yan1513149392** [comment]
感谢处理了该问题，辛苦了
