### ISSUE TITLE
CSS样式没有加载出来

### ISSUE THREAD

**Issue by AdminChenLY** [Hzy0913/mpvue-calendar#58]
示例代码完全复制 也不行
![image](https://user-images.githubusercontent.com/16011242/65024976-67a1e480-d968-11e9-9e26-afd92572c579.png)

**Comment by Hzy0913** [comment]
css引入对了吗？
import  `mpvue-calendar/src/style.css` 引入样式文件(mpvue 小程序端)

**Comment by AdminChenLY** [comment]
已解决   升级了mpvue版本
