### ISSUE TITLE
样式展示问题

### ISSUE THREAD

**Issue by NapleC** [Hzy0913/mpvue-calendar#59]
手机端  multi 模式下 rangeOfMonths设置为两个月，
点击第一个月的日期选中，样式不显示，显示在第二个月里面，取消则无反应

**Comment by NapleC** [comment]
解决方案：multi模式下，在select方法内，
目前是1064行
this.days[k1][k2].selected = !selected;
改为
this.monthRangeDays[monthIndex][k1][k2].selected = !selected;

**Comment by Hzy0913** [comment]
已合并pr
