### ISSUE TITLE
每次在未来月份选择的时候都会跳转到当前月

### ISSUE THREAD

**Issue by PythonNaChen** [Hzy0913/mpvue-calendar#6]
比如现在2018/8/24，我去十月份进行多选，只要一点击某个日期（只要是未来月份的日期），就会立即跳转到当前月份（只有回到十月份，把刚刚点击的日期再次点击取消，之后就能在十月份这哥日历上进行多选，而不会再次跳转到系统当前月了）

**Comment by caohuaqiang1538** [comment]
这块还有个问题，比如先在8月份选择三天，然后在9月份选择三天，再返回到8月份取消掉其中的一天，日历会跳转到9月份去

**Comment by Hzy0913** [comment]
@caohuaqiang1538  谢谢 @1.1.2版本更新，该问题已修复
