### ISSUE TITLE
返回今天点击后，今天的日期没有被选中，打印this.$refs.calendar.setToday()是undefined

### ISSUE THREAD

**Issue by circlewang** [Hzy0913/mpvue-calendar#61]
![image](https://user-images.githubusercontent.com/38183866/65673530-85b0c880-e07d-11e9-8b48-c1857ac9b7c6.png)
如图，点击了回到今天按钮，今天的日期没有被选中，选中状态还停留在上一次点击过得日期，然后打印this.$refs.calendar.setToday()返回undefined，我点击您发的浏览器端，返回今天只会在别的月份返回到今天所在的月份，也不是选中今天，希望可以得到回答

**Comment by circlewang** [comment]
我解决了，利用value来选中今天的日期

**Comment by Hzy0913** [comment]
`setToday` 方法只会返回到今日的日期视图，不会修改`value`，如果要选中需要手动操作
