### ISSUE TITLE
初始化的时候只要有range跟multi就无法成功显示日历

### ISSUE THREAD

**Issue by Madthumb** [Hzy0913/mpvue-calendar#7]
![screen shot 2018-08-28 at 9 04 00 pm](https://user-images.githubusercontent.com/13104722/44759095-0cefdd80-ab06-11e8-9e60-c36e2c73b993.png)

初始化的时候只要有range跟multi就无法成功显示日历，去掉这个2个选项就可以显示
        <calendar
                :months="months"
                :value="value"
                @next="next"
                @prev="prev"
                :events="events"
                lunar="true"
                clean="true"
                @select="select"
                ref="calendar"
                @selectMonth="selectMonth"
                @selectYear="selectYear"
                :arrowLeft="arrowLeft">
        </calendar>

**Comment by Hzy0913** [comment]
查看value格式是否正确传入,range和multi模式下为二维数组
```javascript
<Calendar
  :value="value"
  multi
  ref="calendar"
/>

export default {
    data () {
      return {
        value: [[2018,8,3], [2018,8,21]],
        events: {'2018-6-7':'今日备注', '2018-6-8':'一条很长的明日备注'}
      }
    }
}
```

**Comment by Madthumb** [comment]
@Hzy0913 大神，正好根据你这个回复的例子我有个疑问，怎样才能获得你的events内容？ 比如说你的events规定为： 
```javascript
events: {'2018-6-7':'今日备注', '2018-6-8':'一条很长的明日备注'}
```
然后我想在点击每个日子的时候能获得当前日子是否有events:

```javascript
methods   : {
            select (val, val2) {
                let str   = val.toString()
                let date  = str.replace(/,/g, '-')
                let event = this.events[date]

                console.log(event)  // 这样获得事件的思路是正确的吗？还是说有更好的办法？
            },
```

**Comment by Hzy0913** [comment]
@Madthumb  是的，暂时只支持点击获取当前日期，后续可能会扩展更多信息
