### ISSUE TITLE
插件在网页刷新时报错

### ISSUE THREAD

**Issue by mlb0315** [Hzy0913/mpvue-calendar#70]
原spa项目，通过nuxt改为ssr，如果从路由跳转过去的话，是能正常使用插件的，如果直接浏览器输入含有插件的地址，或者在当前页面中刷新，则会报错 Unexpected token <
如果把import Calendar from "mpvue-calendar";注释掉，就不会报错，不知道怎么改，大佬能帮忙看下吗？？？万分感激！！！

**Comment by mlb0315** [comment]
@Hzy0913

**Comment by Hzy0913** [comment]
能提供案例或者demo吗？
