### ISSUE TITLE
begin禁止时间有问题，知道是什么回事吗

### ISSUE THREAD

**Issue by ZhengHong187** [Hzy0913/mpvue-calendar#71]

**Comment by ZhengHong187** [comment]
begin这个参数传一个求组进去并没有效果发自我的华为手机-------- 原始邮件 --------发件人： 飞翔的荷兰人 <notifications@github.com>日期： 2020年1月17日周五 09:44收件人： Hzy0913/mpvue-calendar <mpvue-calendar@noreply.github.com>抄送： ZhengHong187 <zhenghong187@126.com>, Author <author@noreply.github.com>主    题： Re: [Hzy0913/mpvue-calendar] begin禁止时间有问题，知道是什么回事吗 (#71)具体什么问题呢？

**Comment by ZhengHong187** [comment]
就是我传一个数组进去,没效果类似 begin: [2019, 1, 21] ， dom节点是<Calendar :events='events' @select="select" :value="currentTime" :begin="begin"/>
不知道什么原因

**Comment by Hzy0913** [comment]
我这边没有复现该问题，可以参照一下仓库里的demo https://github.com/Hzy0913/mpvue-calendar/blob/master/example/components/Calendar.vue#L21

**Comment by ZhengHong187** [comment]
不知道，禁止开始开始时间有问题 begin属性发自我的华为手机-------- 原始邮件 --------发件人： 飞翔的荷兰人 <notifications@github.com>日期： 2020年3月16日周一 10:15收件人： Hzy0913/mpvue-calendar <mpvue-calendar@noreply.github.com>抄送： ZhengHong187 <zhenghong187@126.com>, Author <author@noreply.github.com>主    题： Re: [Hzy0913/mpvue-calendar] begin禁止时间有问题，知道是什么回事吗 (#71)
Closed #71.
