### ISSUE TITLE
multi模式，切换月份或年份的时候设置value=[]会报错

### ISSUE THREAD

**Issue by pdmwxy** [Hzy0913/mpvue-calendar#72]
![image](https://user-images.githubusercontent.com/29848359/73592472-d48fd280-4535-11ea-8f8f-d4914c494cef.png)

**Comment by Hzy0913** [comment]
我测试没有复现呢？可以贴下代码吗？

**Comment by Hzy0913** [comment]
清空选中日期已修复，可以尝试安装下`mpvue-calendar@2.3.2`版本
