### ISSUE TITLE
range模式下，怎么清空之前的选中，设置了value=[]会报错

### ISSUE THREAD

**Issue by candyAndBella** [Hzy0913/mpvue-calendar#73]
range模式下，怎么清空之前的选中，设置了value=[]会报错。
range模式下，如果选中了，2020-02-05和2020-02-08这个区间，然后再点一次日期，比如2020-02-10号，没有点第二个日期！！！这时选中的日期就变成了2020-02-10号这天。
实际想要的效果是，之前的区间仍然有效！！！比如退出页面后，再次重新进入，打开日期控件，选中的仍然是2020-02-05和2020-02-08这个区间。现在的效果是2020-02-10这天是选中的！

**Comment by Hzy0913** [comment]
清空选中日期错误已修复，安装`mpvue-calendar@2.3.2`即可。
现在range模式只能选择一个范围，暂不支持多个范围选择。
