### ISSUE TITLE
选择日期和取消日期时，出现月份不规则跳转问题

### ISSUE THREAD

**Issue by luomango** [Hzy0913/mpvue-calendar#74]
比如先在8月份选择三天，然后在9月份选择三天，再返回到8月份取消掉其中的一天，日历会跳转到9月份去

版本 2.2.2 仍然存在这个问题，请问应该怎么解决呢

**Comment by Hzy0913** [comment]
感谢反馈，`@2.3.3`版本已修复该问题

**Comment by luomango** [comment]
谢谢
