### ISSUE TITLE
关于 2.2.3 版本更新后 value 和 select 方法参数返回值错误的问题

### ISSUE THREAD

**Issue by luomango** [Hzy0913/mpvue-calendar#75]
您好，昨天版本更新后出现的问题描述如下：

     我通过将当前月日期通过加入到 value（）数组实现了日历的当前月份全选功能。当我通过全选的按钮，先选择了三月份日期。再选择四月份日期。总天数是通过 select（val1， val2）中 val2 的长度来计算的。此时总天数应该为 三月份天数加四月份天数。如果我返回三月份，手动取消其中的一天，出现的问题是val2 数据返回出错。不等于三月份天数加四月份天数减 1

此问题更新版本前不出现。

**Comment by Hzy0913** [comment]
如果要获取当前所有的选择日期，可以直接读取`value`中的内容，`select`中第二个参数不准确，后期会修复该问题

**Comment by Hzy0913** [comment]
mpvue-calendar@2.3.4 已修复该问题
