### ISSUE TITLE
completion为true时 补足的第六行的农历有bug

### ISSUE THREAD

**Issue by fengdygaga** [Hzy0913/mpvue-calendar#77]
![QQ截图20200408171132](https://user-images.githubusercontent.com/37610687/78766618-11f06080-79bc-11ea-80a5-3693abf42bd9.png)

**Comment by fengdygaga** [comment]
有人碰到过吗 请问怎么解决的呀

**Comment by Hzy0913** [comment]
@fengdygaga  已修复，更新 `mpvue-calendar@2.3.5` 版本

**Comment by fengdygaga** [comment]
> @fengdygaga 已修复，更新`mpvue-calendar@2.3.5`版本

好的 蟹蟹~
