### ISSUE TITLE
设置almanacs时候的相关问题

### ISSUE THREAD

**Issue by fengdygaga** [Hzy0913/mpvue-calendar#78]
![image](https://user-images.githubusercontent.com/37610687/79726853-07b85580-831e-11ea-9458-1a2c1352e8f8.png)
almanacs数据是后台传过来的（这边方便展示直接写死了）
赋值以后就出现问题了，原本应该显示下图的
![image](https://user-images.githubusercontent.com/37610687/79727051-5960e000-831e-11ea-8755-68dbdc5fbc86.png)
结果渲染成下图了
![image](https://user-images.githubusercontent.com/37610687/79727091-6978bf80-831e-11ea-8d20-0fde3a21fd48.png)
点击任意日期后又恢复原样了，这个到底是什么原因呢？
还有almanacs里的值，每年都要变，但是almanacs不支持年份，
所以我想写成如下的需求应该怎么改呀 谢谢作者~
`this.almanacs={ "2020-4-4": "清明","2020-4-5": "清明","2020-4-6": "清明"}`

**Comment by Hzy0913** [comment]
节日一般都是固定日期的，如果是农历节日已经做了处理，节假日是每年会更新，需要定期做数据更新，如果要设置具体到年份的可以使用 `tileContent` 参数

**Comment by Hzy0913** [comment]
我不太好能复现你的问题，可以参考下[demo](https://github.com/Hzy0913/mpvue-calendar/blob/master/example/components/Calendar.vue)里的

**Comment by fengdygaga** [comment]
> 我不太好能复现你的问题，可以参考下[demo](https://github.com/Hzy0913/mpvue-calendar/blob/master/example/components/Calendar.vue)里的

`<template>
    <div>
        <div style="width:400px">
            <Calendar lunar :tileContent="tileContent" :almanacs="almanacs"/>
        </div>
    </div>
</template>

<script>
import Calendar from "mpvue-calendar";
import "mpvue-calendar/src/browser-style.css";
export default {
  components: { Calendar },
  data() {
    return {
      almanacs:'', 
      tileContent: []
    }
  },
  mounted(){
      this.int()
  },
  methods: {
    int(){
        this.almanacs={ "4-12": "复活节"}
        this.tileContent= [
            { date: "2020-4-4", className: "holiday", content: "休" },
            { date: "2020-4-5", className: "holiday", content: "休" },
            { date: "2020-4-6", className: "holiday", content: "休" },
        ]
    }
  }
}
</script>`

int方法中给almanacs赋值后 holiday样式无法渲染出来
作者可以注释掉`this.almanacs={ "4-12": "复活节"}`这行对比下

**Comment by Hzy0913** [comment]
@fengdygaga  感谢反馈，已修复，安装 `mpvue-calendar@2.3.6` 版本

**Comment by fengdygaga** [comment]
@Hzy0913 好的 谢谢作者大大~
我还发现个问题= =  还是上面我回复你贴的那段代码
![1111](https://user-images.githubusercontent.com/37610687/79820062-ee66e600-83bd-11ea-851b-83be611a6477.gif)

4-12日复活节这个节点 初始化的时候没有渲染‘isLunarFestival’这个类名 导致没有样式
点击任意日期后 就渲染上了‘isLunarFestival’这个类名

**Comment by fengdygaga** [comment]
`<template>`
`<div>`
`<div style="width:400px">`
`<Calendar lunar :tileContent="tileContent" :almanacs="almanacs"/>`
`<button @click="changeTileContent">改变tileContent</button>`
`</div>`
`</div>`
`</template>`

`<script>`
`import Calendar from "mpvue-calendar";`
`import "mpvue-calendar/src/browser-style.css";`
`export default {`
`components: { Calendar },`
`data() {`
`return {`
`almanacs:{},`
`tileContent: []`
`}`
`},`
`mounted(){`
`this.int()`
`},`
`methods: {`
`int(){`
`this.almanacs={ "4-12": "复活节"}`
`this.tileContent= [`
`{ date: "2020-4-4", className: "holiday", content: "休" },`
`{ date: "2020-4-5", className: "holiday", content: "休" },`
`{ date: "2020-4-6", className: "holiday", content: "休" },`
`]`
`},`
`changeTileContent(){`
`this.tileContent= [`
`{ date: "2020-4-26", className: "workday", content: "班" },`
`] `
`}`
`}`
`}`
`</script>`

当改变tileContent数据时 页面上无法响应式改变 ，点击任意日期才会改变

**Comment by Hzy0913** [comment]
@fengdygaga 感谢反馈，已修复，更新 `mpvue-calendar@2.3.7` 版本

**Comment by fengdygaga** [comment]
@Hzy0913  好的，谢谢。
