### ISSUE TITLE
不能禁用

### ISSUE THREAD

**Issue by chen2ya** [Hzy0913/mpvue-calendar#9]
<Calendar
              :months="months"
              :value="value"
              @next="next"
              @prev="prev"
              :disabled="disabled"
              :events="events"
              @select="select"
              ref="calendar"
              @selectMonth="selectMonth"
              @selectYear="selectYear"
              v-if="tab.selectedId == '1'"
            />

**Comment by Hzy0913** [comment]
禁用部分日期
```javascript
<template>
  <div>
    <Calendar
      :disabled="disabledArray"
    />
  </div>
</template>


<script>
import Calendar from 'mpvue-calendar'

export default {
  data () {
    return {
      disabledArray: ['2018-6-27','2018-6-25']
    }
  }
}
```
